# Site settings
title:            Angel Solutions Labs
description:      the Big Data Blog From Angel Solutions
logo:             logo.png

# Assign a default image for your site's header and footer
default_bg:       angelcover.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         false
# Turn on or off the fin animations in the header and footer
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
url:              "http://angelsolutions.github.io/labs"
#url:     "http://lpl-ad-dwilliams/design/labs"
#baseurl: "http://lpl-ad-dwilliams/design/labs"
destination: "C:/inetpub/wwwroot/design/labs"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About
    url: /about

# Build settings
markdown: kramdown
highlighter: rouge
