# Site settings
title:            Angel Solutions Labs
description:      Education, technology and business
logo:             logo.png

# Assign a default image for your site's header and footer
default_bg:       angelcover.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         false
# Turn on or off the fin animations in the header and footer
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
url:              "http://angelsolutions.github.io/labs"
destination: "C:/inetpub/wwwroot/design/labs"


# Build settings
markdown: kramdown
highlighter: rouge
